title: TechBlog
description: SeungHunHan

url: https://shhan730.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Kotlin
    url: /tags/kotlin
  - title: Swift
    url: /tags/swift
  - title: Git
    url: /tags/git   

social:
  github: shhan

plugins:
  - jekyll-sitemap
  - jekyll-feed

google_analytics: UA-144771424-2
collections:
  tags:
    output: true
    permalink: /tags/:path/
  authors:
    output: true
    permalink: /authors/:path/
defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
  - scope:
      path: ''
      type: authors
    values:
      layout: author